version: "2"
services:
  influx:
    image: "influxdb:1.3-alpine"
    expose:
      - "8083"
      - "8086"
      - "2003"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
  grafana:
    image: "grafana/grafana:4.4.1"
    ports:
      - "3000:3000"
    links:
      - influx